# Generated by Django 4.2.4 on 2023-09-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0004_remove_vendorprofile_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('Rent', 'For Rent'), ('Sale', 'For Sale')], max_length=4)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], default='Available', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('num_bedrooms', models.PositiveIntegerField()),
                ('num_bathrooms', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('vendor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorprofile')),
            ],
        ),
    ]
