# Generated by Django 4.2.4 on 2023-09-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_address_property_is_published_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='vendor_profile',
            new_name='vendor',
        ),
    ]
