# Generated by Django 4.2.4 on 2023-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='property_status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
