# Generated by Django 4.2.4 on 2023-09-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0003_interest_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='is_interested',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
