# Generated by Django 4.2.4 on 2023-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0004_alter_interest_is_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='initial_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interest',
            name='is_interested',
            field=models.BooleanField(default=False),
        ),
    ]
