# Generated by Django 4.2.4 on 2023-09-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0005_alter_interest_initial_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='initial_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
