# Generated by Django 4.2.4 on 2023-09-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0006_alter_interest_initial_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='property_status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='', max_length=20),
        ),
    ]
