# Generated by Django 4.2.4 on 2023-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0007_alter_interest_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='property_status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('available', 'Available')], max_length=20, null=True),
        ),
    ]
