# Generated by Django 4.2.4 on 2023-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0013_rename_booking_rentbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
