# Generated by Django 4.2.4 on 2023-09-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0014_interest_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertybooking',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
