# Generated by Django 4.2.4 on 2023-09-20 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0009_property_status'),
        ('buyproperty', '0015_propertybooking_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='complete', max_length=20),
        ),
        migrations.CreateModel(
            name='RentPropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='complete', max_length=20)),
                ('booking_payment_id', models.CharField(max_length=100)),
                ('booking_order_id', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now=True)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
