# Generated by Django 4.2.4 on 2023-09-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpayment',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='adminpayment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
