# Generated by Django 4.2.4 on 2023-09-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_vendor'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interested_property',
            field=models.ManyToManyField(blank=True, to='property.property'),
        ),
    ]
