# Generated by Django 4.2.4 on 2023-09-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_vendor'),
        ('user', '0002_userprofile_interested_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interested_property',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_property',
            field=models.ForeignKey(blank=True,null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
            preserve_default=False,
        ),
    ]
