# Generated by Django 4.2.4 on 2023-09-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_interested_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interested_property',
        ),
    ]
