# Generated by Django 4.2.4 on 2023-09-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_vendor'),
        ('user', '0004_remove_userprofile_interested_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property'),
        ),
    ]
